#!/usr/bin/env bash
# scripts/init-env.sh
#
# Interactive initializer for the project .env file. Called via `mise run init-env`.
# - If .env doesn't exist, creates it from .env.example
# - Prompts for each value, defaulting to the current value (or the .env.example value)
# - Validates DATABRICKS_HOST (must start with https://, no trailing slash)
# - Never overwrites silently — prompts before clobbering an existing .env

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
EXAMPLE_FILE="$REPO_ROOT/.env.example"

color() { printf '\033[%sm%s\033[0m' "$1" "$2"; }
bold()  { color '1' "$1"; }
dim()   { color '2' "$1"; }
green() { color '32' "$1"; }
yellow(){ color '33' "$1"; }
red()   { color '31' "$1"; }

if [[ ! -f "$EXAMPLE_FILE" ]]; then
    echo "$(red 'ERROR'): $EXAMPLE_FILE not found. Are you in the repo root?" >&2
    exit 1
fi

# Mode selection if .env already exists
mode="create"
if [[ -f "$ENV_FILE" ]]; then
    echo "$(yellow 'Existing .env found.')"
    echo "  [k]eep current values as defaults and re-prompt (recommended)"
    echo "  [o]verwrite from scratch (lose current values)"
    echo "  [q]uit"
    read -rp "$(bold 'Choice [k/o/q]: ')" choice
    case "${choice,,}" in
        k|"" ) mode="update" ;;
        o    ) mode="create" ;;
        q    ) echo "Aborted." ; exit 0 ;;
        *    ) echo "Unknown choice; aborting." ; exit 1 ;;
    esac
fi

# Read a value out of either .env (if updating) or .env.example (if creating fresh)
read_default() {
    local key="$1" file
    file="$EXAMPLE_FILE"
    [[ "$mode" == "update" && -f "$ENV_FILE" ]] && file="$ENV_FILE"
    grep -E "^${key}=" "$file" 2>/dev/null | tail -n1 | cut -d= -f2- || true
}

# Ask for a single key. Args: KEY "Prompt text" [validator-fn]
ask() {
    local key="$1" prompt="$2" validator="${3:-}"
    local default value
    default="$(read_default "$key")"
    while true; do
        if [[ -n "$default" ]]; then
            read -rp "$(bold "$prompt") [$(dim "$default")]: " value
            value="${value:-$default}"
        else
            read -rp "$(bold "$prompt"): " value
        fi
        if [[ -z "$validator" ]] || "$validator" "$value"; then
            ANSWERS["$key"]="$value"
            return 0
        fi
    done
}

validate_host() {
    local v="$1"
    if [[ ! "$v" =~ ^https://[^/]+$ ]]; then
        echo "  $(red 'Must start with https:// and have no trailing slash.')"
        return 1
    fi
    if [[ "$v" == "https://your-workspace.cloud.databricks.com" ]]; then
        echo "  $(red 'Replace the placeholder with your actual workspace host.')"
        return 1
    fi
    return 0
}

validate_nbdest() {
    local v="$1"
    if [[ ! "$v" =~ ^/Workspace/ ]]; then
        echo "  $(yellow 'Heads up: workspace paths usually start with /Workspace/. Continuing anyway.')"
    fi
    if [[ "$v" == *"you@example.com"* ]]; then
        echo "  $(red 'Replace the example email with your own login.')"
        return 1
    fi
    return 0
}

declare -A ANSWERS=()

echo
echo "$(bold 'Initializing .env for spark-databricks-study')"
echo "$(dim 'Press Enter to accept the [bracketed] default. Ctrl-C to abort.')"
echo

ask DATABRICKS_HOST            "Free Edition workspace URL (no trailing slash)" validate_host
ask DATABRICKS_PROFILE         "Local CLI profile name (DEFAULT is fine)"
ask DATABRICKS_NOTEBOOK_DEST   "Workspace path to import notebooks into"        validate_nbdest
ask DATABRICKS_CATALOG         "Catalog to write lab tables into"
ask DATABRICKS_SCHEMA          "Schema to write lab tables into"

# Write the file (atomic via temp + mv)
tmp="$(mktemp "${ENV_FILE}.XXXXXX")"
cat > "$tmp" <<EOF
# Generated by scripts/init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edit by hand or rerun: mise run init-env

DATABRICKS_HOST=${ANSWERS[DATABRICKS_HOST]}
DATABRICKS_PROFILE=${ANSWERS[DATABRICKS_PROFILE]}
DATABRICKS_NOTEBOOK_DEST=${ANSWERS[DATABRICKS_NOTEBOOK_DEST]}
DATABRICKS_CATALOG=${ANSWERS[DATABRICKS_CATALOG]}
DATABRICKS_SCHEMA=${ANSWERS[DATABRICKS_SCHEMA]}
EOF
chmod 600 "$tmp"
mv "$tmp" "$ENV_FILE"

echo
echo "$(green '✓') Wrote $(bold "$ENV_FILE") with mode 0600 (owner-only)."
echo
echo "Next steps:"
echo "  $(bold 'mise run db:login')     # OAuth into your workspace"
echo "  $(bold 'mise run db:whoami')    # confirm auth worked"
echo "  $(bold 'mise run db:import')    # push notebooks/databricks/ into the workspace"
